{
  "language": {
    "name": "python",
    "engine": "CPython",
    "version": "3.8.19"
  },
  "client": {
    "name": "appmap",
    "url": "https://github.com/applandinc/appmap-python"
  },
  "git": {
    "repository": "https://github.com/land-of-apps/django-oscar.git",
    "branch": "master",
    "commit": "01aa57720e1e703bdc166b20350eff665be60dad"
  },
  "frameworks": [
    {
      "name": "pytest",
      "version": "7.4.4"
    },
    {
      "name": "Django",
      "version": "4.2.13"
    }
  ],
  "feature_group": "An anonymous user",
  "recording": {
    "defined_class": "tests.functional.customer.test_order_status.TestAnAnonymousUser",
    "method_id": "test_gets_404_when_using_incorrect_hash"
  },
  "source_location": "tests/functional/customer/test_order_status.py:25",
  "name": "An anonymous user gets 404 when using incorrect hash",
  "feature": "Gets 404 when using incorrect hash",
  "app": "django-oscar",
  "recorder": {
    "name": "pytest",
    "type": "tests"
  },
  "test_status": "succeeded"
}