[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Must be an AttributeOption model object instance']",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:1046"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Must be an AttributeOption model object instance']",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:1086",
      "src/oscar/apps/catalogue/abstract_models.py:1046"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Must be an AttributeOption model object instance']",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:1097",
      "src/oscar/apps/catalogue/abstract_models.py:1086",
      "src/oscar/apps/catalogue/abstract_models.py:1046"
    ]
  }
]