[
  {
    "class": "builtins.ValueError",
    "message": "There is already an order with number 1234",
    "stack": [
      "src/oscar/apps/order/utils.py:43"
    ]
  }
]