[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['%s is a reserved name and cannot be used as an attribute']",
    "stack": [
      "src/oscar/apps/catalogue/product_attributes.py:159"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['8_oepla is not a valid identifier, but attribute codes must be valid python identifiers']",
    "stack": [
      "src/oscar/apps/catalogue/product_attributes.py:159"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['bina-weight is not a valid identifier, but attribute codes must be valid python identifiers']",
    "stack": [
      "src/oscar/apps/catalogue/product_attributes.py:159"
    ]
  }
]